# Generated by Django 2.0.2 on 2018-02-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newboston', '0003_auto_20180214_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(upload_to='fs'),
        ),
    ]
