# Generated by Django 2.0.2 on 2018-02-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newboston', '0004_auto_20180214_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
