# Generated by Django 2.0.2 on 2018-02-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newboston', '0006_auto_20180214_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
